task:
    name: Test IP
    timeout_in: 120m
    container:
        cpu: 8
        memory: 32G
        image: docker.io/ubuntu
        kvm: true
    script: 
        - apt-get update &>/dev/null
        - apt install unzip wget curl sudo -y &>/dev/null
        - curl -s4m8 ipinfo.io
