task:
    name: Test IP
    timeout_in: 120m
    container:
        cpu: 8
        memory: 32G
        image: docker.io/ubuntu
        kvm: true
    script: 
        - apt-get update &>/dev/null
        - apt install unzip wget curl sudo -y &>/dev/null
        - apt install -y qemu-kvm &>/dev/null
        - wget -O ngrok-stable-linux-amd64.zip https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip &>/dev/null && unzip -o ngrok-stable-linux-amd64.zip &>/dev/null
        - ./ngrok authtoken 24PL0NgOrz7JprSOL67fPCQ1zG4_4usme1vy42H7ehKb4P6mT &>/dev/null
        - nohup ./ngrok tcp --region ap 30889 &>/dev/null &
        - sudo wget -O win7.img https://link.jscdn.cn/sharepoint/aHR0cHM6Ly9jYW1wdXNtY2NkLW15LnNoYXJlcG9pbnQuY29tLzp1Oi9nL3BlcnNvbmFsL2xpbmRhX3JpY2hfY2FtcHVzX21jY2RfZWR1L0VSTW5BdjZUVDlsRnNPYzljSGJhaVZJQjN0dHdQM0RzZDZ1OGFBTXpYa0c3N2c_ZT1WWmEyUng.img &>/dev/null
        - nohup sudo qemu-system-x86_64 -net nic -net user,hostfwd=tcp::30889-:3389 -show-cursor -m 16G -enable-kvm -cpu host,hv_relaxed,hv_spinlocks=0x1fff,hv_vapic,hv_time,+nx -M pc -smp cores=4 -vga std -machine type=pc,accel=kvm -usb -device usb-tablet -k en-us -hda win7.img -boot once=d -vnc :0
